name: chat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  injectable: ^2.1.0
  injectable_generator: ^2.1.3
  logger: ^1.4.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter-light.otf
          weight: 300
        - asset: assets/fonts/inter-regular.otf
          weight: 400
        - asset: assets/fonts/inter-medium.otf
          weight: 500